### PR TITLE
Keep search parameter on cache entry detail link.

### PR DESCRIPTION
**Pull request by DennisBirkholz**
Detail/entry content then works for cache entries that are not on the first page of the unfiltered list.

### CODE REVIEW

**Comment by DennisBirkholz** [comment]
I renamed the newly introduced variable to better show its meaning.
I also fixed indentation/whitespace with a separate commit.

As my changes (or the addresses problem) did not seem to explain itself, a short description of the problem:

Lets assume you have 26 entries in your cache: `entry_a` to `entry_z`. If you now search for `z` only `entry_z` is displayed on the result page. If you now click on `entry_z` to view its contents, your search is discarded and you are back to a list view. If `entry_z` happens to be in the entries of that view, its contents is displayed, otherwise not.

My patch now keeps the search string in the link to display the entry detail so if you click on an entry, you see the same search result list but with the clicked entry expanded.

**Comment by nikic** [comment]
Sounds reasonable, but I won't be able to test and merge this until next week.

**Comment by DennisBirkholz** [comment]
> I won't be able to test and merge this until next week.

No problem, have a nice easter holiday ;-)

**Comment by nikic** [comment]
Thanks!

**Pull request merged**
