### PR TITLE
Appveyor x64 test

### PR DESCRIPTION
**Pull request by Jan-E**
Try to test x64 build on Windows

### CODE REVIEW

**Comment by Stricted** [comment]
"Fatal error: Uncaught Error: Call to undefined function apcu_store() in C:\projects\php-src\ext\apcu\tests\apc_014_store_ref.php:10" thats weird :D

**Comment by Stricted** [comment]
could you add
```environment:
  REPORT_EXIT_STATUS: 1
```
to the appveyor.yml ? (that will make the build fail when the tests failing)

**Comment by Stricted** [comment]
@Jan-E i got it working https://github.com/Stricted/apcu/commit/9bdbf85f49fb111b3792d2da81c852f72b57f2e0
x86: https://ci.appveyor.com/project/Stricted/apcu/build/job/ogxkwy6bfm55gq5q
x64: https://ci.appveyor.com/project/Stricted/apcu/build/job/a5v6l68dome84e9g
i will merge this later into master

**Comment by Jan-E** [comment]
Closed in favour of a new PR: https://github.com/krakjoe/apcu/pull/240

**Pull request closed without merging**
