### PR TITLE
fix APC compatibility

### PR DESCRIPTION
**Pull request by Stricted**
see https://github.com/krakjoe/apcu/commit/4f47d6dea51cf00ab13e623a6dd91c3d96c0fcc4#commitcomment-8126847

### CODE REVIEW

**Comment by mishan** [comment]
:+1:

**Comment by mishan** [comment]
@krakjoe

**Comment by Stricted** [comment]
@krakjoe ...

**Comment by mishan** [comment]
It'd be nice to keep keys compatible between APC and APCu so similar/same status pages can be used.

**Pull request closed without merging**
