### PR TITLE
Fixed build with BC disabled 

### PR DESCRIPTION
**Pull request by tony2001**
The patch just fixes the code so that it would compile with PHP7.

But I must note that BC doesn't quite work - changing the module hash from within hash_apply() produces these warnings and a crash for me:

==32026== Invalid read of size 1
==32026==    at 0x63F3C0: zend_hash_apply (zend_hash.c:1459)
==32026==    by 0x631DF9: zend_startup_modules (zend_API.c:1955)
==32026==    by 0x5D00C5: php_module_startup (main.c:2194)
==32026==    by 0x6C64C4: php_cgi_startup (fpm_main.c:837)
==32026==    by 0x42DADC: main (fpm_main.c:1788)
==32026==  Address 0x74bbff8 is 8 bytes after a block of size 1,152 free'd
==32026==    at 0x4C2970C: free (vg_replace_malloc.c:468)
==32026==    by 0x6391C4: zend_hash_do_resize (zend_hash.c:825)
==32026==    by 0x639BB7: _zend_hash_add (zend_hash.c:536)
==32026==    by 0x633862: zend_register_module_ex (zend_hash.h:546)
==32026==    by 0xCD35FED: apc_init (php_apc.c:1116)
==32026==    by 0xCD348A6: zm_startup_apcu (php_apc.c:304)
==32026==    by 0x631A81: zend_startup_module_ex (zend_API.c:1829)
==32026==    by 0x63F3D1: zend_hash_apply (zend_hash.c:1460)
==32026==    by 0x631DF9: zend_startup_modules (zend_API.c:1955)
==32026==    by 0x5D00C5: php_module_startup (main.c:2194)
==32026==    by 0x6C64C4: php_cgi_startup (fpm_main.c:837)
==32026==    by 0x42DADC: main (fpm_main.c:1788)

### CODE REVIEW

**Comment by krakjoe** [comment]
I think another solution might be to have a normal module for apc bc, registered in the normal way with it's own config.m4, I'm not quite sure how to go about that just yet ... anyone have a clue ?

**Comment by tony2001** [comment]
Uhm.. Just noticed that the pull request is done to the wrong branch. Let me know if you want me to fix it.

**Comment by krakjoe** [comment]
Please do fix it ... thanks :)

**Comment by tony2001** [comment]
Ok, done - see PR #133 .
Regarding the BC - do you really think it should be done at all?
I'm not sure with all these code changes you need to keep this particular part backward compatible at all cost.

**Comment by krakjoe** [comment]
Are you suggesting we drop apc module completely ?

**Comment by tony2001** [comment]
Yep. This is apcu and it's a different thing IMO.

**Comment by krakjoe** [comment]
I had considered it, if we don't make the distinction now, we have to carry the awkwardness for another decade or whatever ... I think we'll just drop apc compat then ...

**Pull request closed without merging**
